# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [115]:
import numpy as np

In [15]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
contiene_valor_0 = np.where(a == 0)
print("Contiene el valor 0: ", contiene_valor0)

Contiene el valor 0:  (array([], dtype=int64),)


In [30]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
valor_diferente_a_0 = np.where(a != 0)
print("El arreglo contiene valores diferentes a 0 en el indice:", valor_diferente_a_0 )

El arreglo contiene valores diferentes a 0 en el indice: (array([2]),)


In [26]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
contiene_inf = np.isinf(a).any()
contiene_nan = np.isnan(a).any()

print (f"El arreglo contiene los valores Inf y NaN: {contiene_inf} y {contiene_nan}")

El arreglo contiene los valores Inf y NaN: True y True


In [32]:
#ejercicio 4
a = np.array([1, 2, np.inf])
contiene_inf = np.isinf(a).any()
print (f"El arreglo contiene valores infinitos: {contiene_inf}")

El arreglo contiene valores infinitos: True


In [33]:
#ejercicio 5
a = np.array([1, np.nan, 3])
contiene_nan = np.isnan(a).any()
print (f"El arreglo contiene valores NaN: {contiene_nan}")

El arreglo contiene valores NaN: True


In [13]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
mayor = a > b
mayor_o_igual = a >= b
menor= a < b
menor_o_igual    = a <= b

print("a > b :", a[mayor])
print("a >= b :", a[mayor_o_igual])
print("a < b :", a[menor])
print("a <= b :", a[menor_o_igual])

a > b : [5]
a >= b : [3 5]
a < b : [1]
a <= b : [1 3]


In [18]:
#ejercicio 7
a = np.array([1, 7, 13, 105])
print (f"El arreglo ocupa la cantidad de memoria de: {a.nbytes} bytes")

El arreglo ocupa la cantidad de memoria de: 32 bytes


In [29]:
#ejercicio 8
a_ceros = np.zeros([10])
a_unos = np.ones([10])
a_cincos = a_unos * 5
print (f" Arreglo de ceros: {a_ceros}")
print (f" Arreglo de unos: {a_unos}")
print (f" Arreglo de cincos: {a_cincos}")

 Arreglo de ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 Arreglo de unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 Arreglo de cincos: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [59]:
#ejercicio 9
a = np.arange(30, 71)
print (f" Arreglo con todos los numeros enteros de entre el 30 y 70: {a}")

 Arreglo con todos los numeros enteros de entre el 30 y 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [60]:
#ejercicio 10
a = np.arange(30, 71, 2)
print (f" Arreglo con todos los numeros pares de entre el 30 y 70: {a}")

 Arreglo con todos los numeros pares de entre el 30 y 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [37]:
#ejercicio 11
a = ([1, 0, 0], [0, 1, 0], [0, 0, 1])
matriz_identidad = np.array(a)
matriz_identidad

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
#ejercicio 12
import random
n_aleatorio = np.random.rand(1)
print (f'Numero aleatorio generado entre 0 y 1: {n_aleatorio}')


Numero aleatorio generado entre 0 y 1: [0.19370808]


In [50]:
#ejercicio 13
a = np.random.rand(1,15)
print (f'arreglo de 15 números aleatorios tomados de una distribución normal estándar: {a}')

arreglo de 15 números aleatorios tomados de una distribución normal estándar: [[0.15357184 0.44434252 0.67594516 0.01822711 0.77490575 0.33569778
  0.52583663 0.60599651 0.07880297 0.78112941 0.64606792 0.77140256
  0.2080596  0.07370884 0.35122236]]


In [68]:
#ejercicio 14
a = np.linspace(start=15, stop=55, num=10, dtype=int)
a_modificado = a[1: -1]
print (f"Arreglo con valores entre el 15 y 55 sin mostrar el primer y ultimo valor: {a_modificado}")

Arreglo con valores entre el 15 y 55 sin mostrar el primer y ultimo valor: [19 23 28 32 37 41 46 50]


In [72]:
#ejercicio 15
a = np.linspace(start=5, stop=50, num=10)
print (f'Arreglo de longitud 10 con valores equitativamente distribuidos entre 5 y 50: {a}')

Arreglo de longitud 10 con valores equitativamente distribuidos entre 5 y 50: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [107]:
#ejercicio 16 
a = np.arange(0, 20)
rango = (a >= 9) & (a <= 15)
a[rango] = a[rango] * -1
a


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19])

In [108]:
#ejercicio 17
a = np.array([1, 2, 3])
lista_python = a.tolist()
lista_python

[1, 2, 3]

In [109]:
#ejercicio 18
l = [1, 2, 3]
a = np.array(l)
a

array([1, 2, 3])

In [121]:
#ejercicio 19
m = np.array([[1, 2], [3, 4]])
valores_par = m % 2==0
m[valores_par]

array([2, 4])

In [125]:
#ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])
filas =m.shape[0]
columnas =m.shape[1]
print (f'El numero de filas y columnas del array {m}  son: {filas} filas y {columnas} columnas')

El numero de filas y columnas del array [[1 2 3]
 [4 5 6]]  son: 2 filas y 3 columnas
